name: Bug Report
description: Create a bug report.
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Expected Result
            description: A clear and concise description of what you expected to happen
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Mod Version
            description: The version of the mod you were using when the bug occured
            placeholder: 1.0.0
        validations:
            required: true
    -   type: input
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            placeholder: 1.19.4
        validations:
            required: true
    -   type: input
        attributes:
            label: Loader
            description: The modloader you were using when the bug occured
            placeholder: Forge
        validations:
            required: true
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to fill out this bug report and to help improve the mod!!"
